### ISSUE TITLE
Cannot viewm meetings which have attendees that are not in the filtered persons list

### ISSUE THREAD

**Issue by jason-raiin** [AY2324S1-CS2103T-F12-4/tp#109]

**Comment by howenc** [comment]
Is this still happening?

**Comment by howenc** [comment]
<img width="425" alt="image" src="https://github.com/AY2324S1-CS2103T-F12-4/tp/assets/107026005/ff20b5ad-b1ab-40af-bd5d-e9484d622324">
seem ok now
