### ISSUE TITLE
[PE-D][Tester D] Bug in find meeting feature

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-F12-4/tp#133]
There is no exception thrown when I give wrong format for the start time of the meeting. It still shows me all the meetings in addressbook. You might want to handle that exception.

![image.png](https://raw.githubusercontent.com/erohsikivar/ped/main/files/803a3780-6c71-4318-86df-cfe36a018eef.png)

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: erohsikivar/ped#6

**Comment by howenc** [comment]
Should I say that the if no start or end is given, the program will assume start to be start of time and end to be end of time.
So that they can search independently?
