### ISSUE TITLE
[PE-D][Tester A] Inaccurate addc quickstart

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-F12-4/tp#149]
![image.png](https://raw.githubusercontent.com/H1410101/ped/main/files/d391aff3-5d9a-4353-8a27-cca61c375c5e.png)

Also tried:
`addc n/John Doe p/92345123 e/asdasdasd@example.com lc/18.09.2023 1500 o/NUS`

EDIT: quick start suggested the command above, with `o/`, but I guess it isn't supposed to be there

EDIT EDIT: command summary also has the same problem, including `o/`, but also including `add` instead of `addc`

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: H1410101/ped#2

**Comment by LoMaply** [comment]
Fixed in #153
