### ISSUE TITLE
Modify default add command to addc

### ISSUE THREAD

**Issue by LoMaply** [AY2324S1-CS2103T-F12-4/tp#45]
In addition, the a/ADDRESS argument should be changed to o/ORGANISATION unless we want to have both

**Comment by jason-raiin** [comment]
i dont think theres an address field currently? but regardless we'll have to add o/ORGANISATION in the future

**Comment by LoMaply** [comment]
> i dont think theres an address field currently? but regardless we'll have to add o/ORGANISATION in the future

Ah I guess someone already removed the address field since it is present in the original AB3
