### ISSUE TITLE
Clear command for Meetings

### ISSUE THREAD

**Issue by LoMaply** [AY2324S1-CS2103T-F12-4/tp#48]
Clear command will likely clear all Meetings, similar to the current clear command from AB3.

May instead remove the clear command entirely.

**Comment by jason-raiin** [comment]
`clear` command implementation currently generates a new `AddressBook` so both persons and meetings are cleared, is this the envisioned behaviour for this?

**Comment by LoMaply** [comment]
> `clear` command implementation currently generates a new `AddressBook` so both persons and meetings are cleared, is this the envisioned behaviour for this?

Not sure if we want to even have this

**Comment by jason-raiin** [comment]
closed for now, can revisit in the future
